/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package something;

import org.riversun.slacklet.Slacklet;
import org.riversun.slacklet.SlackletRequest;
import org.riversun.slacklet.SlackletResponse;
import org.riversun.slacklet.SlackletService;
import org.riversun.xternal.simpleslackapi.SlackChannel;

import java.io.IOException;

public class App {
    public static void main(String[] args) {
        String botToken = System.getenv("SLACK_API_TOKEN");

        SlackletService slackService = new SlackletService(botToken);

        // slackletを追加する
        slackService.addSlacklet(new Slacklet() {
            Bot bot = new Bot();
            @Override
            public void onMessagePosted(SlackletRequest req, SlackletResponse resp) {
                var r = bot.onMessagePosted(req.getContent(), req.getChannel().getName(), req.getUserDisp());
                r.ifPresent(resp::reply);
            }

            @Override
            public void onMentionedMessagePosted(SlackletRequest req, SlackletResponse resp) {
                var r = bot.onMentionedMessagePosted(req.getContent(), req.getChannel().getName(), req.getUserDisp());
                r.ifPresent(resp::reply);
            }
        });

        // slackletserviceを開始(slackに接続)
        System.out.println("starting");
        try {
            slackService.start();
        } catch (IOException e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
        System.out.println("started");
    }
}
